apiVersion: keikoproj.io/v1
kind: FlippyConfig
metadata:
  name: flippy-sample
  namespace: istio-system
spec:
  # Add fields here
  ImageList:
    - docker.intuit.com/flippy/sample:abc
    - docker.intuit.com/flippy/sample:pqr
  PostFilterRestarts:
    - K8S:
        Type: Deployment
        Name: istio-ingressgateway
        Namespace: istio-system
      StatusCheckConfig:
        CheckStatus: true
        MaxRetry: 10
        RetryDuration: 30
  Preconditions:
    - K8S:
        Type: Deployment
        Name: istiod
        Namespace: istio-system
      StatusCheckConfig:
        CheckStatus: true
        MaxRetry: 10
        RetryDuration: 30
  RestartObjects:
    - Type: Deployment
      StatusCheckConfig:
        CheckStatus: false
        MaxRetry: 10
        RetryDuration: 30
    - Type: ArgoRollout
      StatusCheckConfig:
        CheckStatus: false
        MaxRetry: 10
        RetryDuration: 30
  ProcessFilter:
    Containers:
      - istio-proxy
    Labels:
      "istio-injection": "enabled"
    Annotations:
      "sidecar.istio.io/inject": "true"
