name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    if: github.repository_owner == 'keikoproj'
    name: unit-test
    runs-on: ubuntu-22.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.24

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: go

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Test
      run: |
        make tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.txt
        token: ${{ secrets.CODECOV_TOKEN }}
